scripts/client/_otter_env_core.sh
As _otter_env_core.sh_ stands, running _otter_ overwrites whatever might have been present in $PERL5LIB. This is a problem _e.g._ if one uses this variable to make Perl aware of the install directory used by cpanminus. This PR ensures that the original value of PERL5LIB is preserved.
This is related to the _otter-client_ PR Ensembl/otter-client#1.
=> _otter_env_core.sh: do not clobber existing PERL5LIB

t/etc/test_regions/human_test:chr2-38:929903-1379472.xml, t/lib/Test/Bio/Vega.pm
The CoordSystemFactory module has been changed to not have the hard coded coord_systems.
I updated the data to add coord_system_name and coord_system_version to the XML file and I am providing a coord_system with override_spec
=> Fix tests for XMLToRegion

modules/Bio/Vega/Gene.pm, modules/Bio/Vega/Transcript.pm
The status and is_known method have been removed from the Ensembl Core API around release 90. These methods are needed for Otter to work. They might be removed in the future with a change in the client and the server as the status might not be relevant anymore.
This PR replace PR #27
=> Add status and is_known methods to Bio::Vega::Gene and Bio::Vega::Transcript

.travis.yml
We do not actually USE Perl here, all the testing happens inside a Docker container. Just get rid of it, at the very least it will save our builds some time and bandwidth.
=> Remove Perl directives from .travis.yml [master]

.travis.yml
We do not actually USE Perl here, all the testing happens inside a Docker container. Just get rid of it, at the very least it will save our builds some time and bandwidth.
=> Remove Perl directives from .travis.yml [feature/ensembl_friendly]

modules/Bio/Otter/Lace/SequenceSet.pm
Remove the default chromosome and Otter so we use the coord system version and name from the object
=> Retrieve the coord system name and version

scripts/apache/get_clonesequences
Code to handle ENSCORESW-2978.
The code has two ways of fetching the clones from the assembly. The preferred method is to use the get_MiscFeatureAdaptor. There is a difference in number of clones fetched by the SQL query and the adaptor.
=> Code to handle clone fetching from the assembly level.

modules/Bio/Vega/Transform/FromHumAce.pm
Since release/85 get_all_Transcripts returns an arrayref on the copy
of the array of transcripts array instead of the actual reference.
So when the code was deleting the old_gene using later version of the
code it was also deleting the transcripts. This was not intended.
This has been lightly tested
=> Use flush_Transcripts method to correctly empty the _transcript_array

modules/Bio/Vega/Utils/EnsEMBL2GFF.pm
In Ensembl, the repeat masker analysis is repeatmask_repbase or
repeatmask_* so the previous regex looking for RepeatMasker does
not work anymore
This is some code I had for some time, it should fix ENSCORESW-3208
=> Use RepeatMask instead of RepeatMasker in regex

modules/Bio/Vega/Transform/RegionToXML.pm
When the Otter XML is created, it wants strand to be set for every
object but some Ensembl objects do not have their strand set as the
strand does not matter in some case. So we just set it to 1 for
simplicity
It may not me useful for human and mouse but it is needed when working on new species
=> Set strand to 1 if not defined in object

scripts/apache/get_clonesequences
Most functions in the Core API return objects sorted on forward strand,
5' to 3', but not the misc_feature. It also need the meta_key
misc_featurebuild.level to be set to toplevel.
It will need version 37 of the database for the fix to really work
=> Sort misc_feature before creating object

scripts/apache/get_analyses_status
The contig names have been changed in NoMerge to match their real
name. So we need to update get_analysis_status to reflect this
modification
Removed unused variables
It will need version 37 of the database for the fix to really work
=> Remove .1.<length> in the contig name of input_id_analysis

modules/Bio/Vega/Transform/RegionToXML.pm
The merge process is keeping all Havana genes so a ensembl_havana
gene is like a havana gene. Thus we want the merge genes to be seen
as normal havana genes.
Without this patch most of the genes will not be visible with version 37
=> Object of source ensembl_havana to be seen as havana

modules/Bio/Vega/DBSQL/StableIdAdaptor.pm
Resolving issue https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3036 , 
generally stableIds are obtained from meta table, the only place where it is hardcoded and needs replace - is here.
=> Replace hardcoded stable ids prefix

modules/Bio/Vega/Transform/RegionToXML.pm, modules/Bio/Vega/Transform/XMLToRegion.pm, modules/Bio/Vega/Utils/EnsEMBL2GFF.pm, modules/MenuCanvasWindow/SessionWindow.pm, t/etc/test_regions/human_test:chr12-38:30351955-34820185.xml, t/etc/test_regions/human_test:chr2-38:929903-1379472.xml, t/etc/test_regions/human_test:chr6-38:2557766-2647766.xml, t/etc/test_regions/mouse:chr1-38:3009920-3786391.xml
By default the source is havana. Because we are working on NoMerge,
the source in the Loutre database can be ensembl_havana, havana or
ensembl. When an annotator modify an ensembl transcript, it becomes
an ensembl_havana transcript and the gene also has the ensembl_havana
source.
There is some hack for the client so it send a message to Zmap so the
transcript is redrawn is the correct track
=> Add source to XML and modify the source based on the annotation

modules/Bio/Vega/Region/Ace.pm, modules/Bio/Vega/Transform/FromHumAce.pm, modules/MenuCanvasWindow/SessionWindow.pm
There is some code to update the source of a gene, this could be
modified when the Core API can update the source when calling
'update'
=> Check old transcript and gene before updating source of new objects

modules/MenuCanvasWindow/SessionWindow.pm, modules/MenuCanvasWindow/TranscriptWindow.pm
In SessionWindow.pm, where the transcript is updated, `$new_subseq->Locus->gene_type_prefix = ' '`. I'm unsure if this has to be reset. 
Further testing is required.
=> Code to fix unnecessary save trigger when an ensembl transcript is opened

modules/Bio/Vega/DBSQL/StableIdAdaptor.pm
The code now generates the stable ID with the correct length. This has been tested and approved by the annotators.
=> Code to generate correct Ensembl stable ID

modules/MenuCanvasWindow/SessionWindow.pm
When the locus symbol is changed, it does not get updated in the locus cache. This causes issue when trying to fix the gene_type_prefix for the new locus. This PR fixes this issue. Extensive testing will be required.
=> The code adds the new locus to the locus cache

modules/Bio/Vega/DBSQL/StableIdAdaptor.pm
Resolving issues 3370, 3410, 3460.
In all this cases we are having error: 'DBD::SQLite::db prepare failed: near ")": syntax error .....
It is caused when we are executing at sqlite expression `insert into $table () values()` - which is not valid for new version of sqlite, and means inserting of default values.
So the fix is to replace with correct sqlite query for default values insert.
=> Default values insert replaced with new syntax

modules/Bio/Otter/Lace/AceDatabase.pm
When we got only one locus entry, it is not on the second level of hash, but on first, without name key. FIxed with converting to expected hash. Issues 3478, 3454, 3403
=> Processing case with only one locus entry

scripts/apache/nfetch
FetchDB in ZMap and Blixem did not work because of Sanger authentication in the code. This has been resolved by removing those code lines.
=> Changes made for fetchdb to work in ZMap

modules/Bio/Vega/Exon.pm, modules/Bio/Vega/Transcript.pm
The new_dissociated_copy method in Exon and Transcript was not copying
the supporting evidence. So the supporting evidences would be lost each
time the method is used
This addition may have an impact on the performance of the code as some models will have many supporting evidence. So maybe it is better to have it as a new method
=> Add supporting evidences when cloning object

modules/Bio/Otter/Auth/SSO.pm, modules/Bio/Otter/Lace/Client.pm
This is a temporary fix to get the authentication process working. The authentication server has been changed. The token verification has been bypassed for the time being. This will be fixed when changes are made to production server.
=> Temporary changes to the authentication process

modules/Bio/Otter/Server/UserSpecies.pm
A new database is being integrated into Otter for training purposes, which will be called `human_training` in Otter.
`human_training` is being added in here as a new 'species'  to UserSpecies.pm, which will hopefully allow Otter to recognise this as a new database to request access to.
=> Add human_training db to species list

modules/Bio/Otter/Server/UserSpecies.pm
Investigations of a 417 error have found that Test Otter does not have access to the new human_training data set. These changes are to be pushed against the code branch `test_server_client` so that Test Otter can access this data set (already pushed to master and working fine for Production Otter).
=> Add human_training to species list for Test Otter

modules/Bio/Otter/Lace/Client.pm, modules/Bio/Otter/Lace/OnTheFly/QueryValidator.pm, modules/Bio/Otter/UI/OnTheFlyMixin.pm, modules/EditWindow/Exonerate.pm, scripts/apache/get_fasta_sequence
We now can choose the sequence type DNA and Protein in the OTF window. If we select DNA sequence type (selected by default) in OTF window then DNA sequence from refseq and ena servers are fetched and aligned. If we select protein then only protein sequence from Uniprot is fetched and aligned.
=> Sequence type selection for OTF

modules/Bio/Otter/Lace/OnTheFly/QueryValidator.pm
If there is no sequence present for a sequence type (DNA, protein) display a hint to switch the sequence type
=> Change error message when sequence not found

modules/Bio/Otter/Utils/BulkMM.pm, modules/Bio/Otter/Utils/MM.pm
This PR is to reconfigure connection details for M&M DB to point to the new DB host.
Pls, see https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-4114
The Otter test server has already moved to the new host, and it is working fine.
To test all is good - after Otter reboot - it is sufficient to open a region on Zmap.
Roll changes back (revert the PR, pull changes, and restart the server)
=> Changed MM DB host
