modules/Bio/Otter/Auth/SSO.pm
modules/Bio/Otter/Lace/Client.pm
modules/Bio/Otter/Server/UserSpecies.pm

Fixed authentication/authorization error for Dotter, Zmap and OTF. I have removed the seqtools tar file as it is not required for this repo.

Authorization error fix for Dotter, Zmap and OTF

---

modules/Bio/Otter/Server/Config.pm
modules/Bio/Otter/Server/UserSpecies.pm

This change will remove all DB details from ensembl-otter

Changes made to hide DB details in userspecies

---

modules/Bio/Otter/Lace/Defaults.pm
modules/Bio/Otter/Server/UserSpecies.pm

License added to Userspecies.pm. URL changed to server URL.

Added license and changed server URL

---

modules/Bio/Otter/Auth/SSO.pm
modules/Bio/Otter/Lace/Client.pm
modules/Bio/Otter/Lace/Defaults.pm
modules/Bio/Otter/Server/UserSpecies.pm
modules/MenuCanvasWindow/SessionWindow.pm

Repeated password request issue has been resolved.

Changes made to resolve cookie expiry issue

---

modules/Bio/Otter/Auth/SSO.pm

Fixed login issue with passwords that have special characters.

Fixed password issue with special characters

---

modules/Bio/Otter/Lace/Client.pm

Annotator can save changes with this fix.

Bug fix for saving otter annotation changes

---

modules/Bio/Otter/Fetch/BigWig.pm
modules/Bio/Otter/Lace/AceDatabase.pm
modules/Bio/Otter/Lace/Defaults.pm
modules/Bio/Otter/Mapping.pm
modules/Bio/Otter/Server/Support/Web.pm
modules/Bio/Otter/Utils/GetScript.pm

Code changes to process Bigwig and BAM files. Changed write access to default value of 0.

Bigwig and BAM files processing issue fix

---

modules/Bio/Otter/Lace/Client.pm
modules/Bio/Otter/Utils/GetScript.pm
scripts/client/_otter_env_core.sh

1. Changes made to GetScript.pm to process BAM files
2. Changes made to Client.pm and _otter_env_core.sh to hack proxy issues. Will revert to original once I find a better solution.

Few more fixes to process BAM files

---

modules/Bio/Otter/Utils/BulkMM.pm
modules/Bio/Otter/Utils/GetScript.pm
modules/Bio/Otter/Utils/MM.pm
scripts/lace/prefix_evidence_with_Sw_Tr_Em.pl

BAM script authorization issue fix.

Changes made to access MM db and fix BAM script authorization issue

---

scripts/apache/nfetch

Code to fix Fetch DB Entry error

Fix for Fetch DB error

---

modules/Bio/Otter/Utils/BulkMM.pm
modules/Bio/Otter/Utils/MM.pm

This fix should resolve cross species OTF error

OTF Bug fix

---

modules/EditWindow/FetchDb.pm
modules/MenuCanvasWindow/SessionWindow.pm
scripts/apache/get_sequence

Fetch db shortcut fix, and clear box

Fetch db: Clear box before sequence view, shorcut changed

---

modules/Bio/Otter/Lace/OnTheFly/QueryValidator.pm

Oft bug fix

---

.travis.yml

Removes yet another install script to sync changes into + will hopefully make Travis builds for this and derived branches great again... I mean, work. See ENSCORESW-3143.

feature/ensembl_friendly: Copy Travis configuration from master

---

modules/Bio/Otter/Lace/DB.pm

ENSCORESW-3025- New set of clones can be loaded once the older set has been loaded on ZMap.

With this fix new set of clones can be loaded

---

scripts/apache/get_sequencesets

These changes will list all the chromosomes in the NoMerge DB. It does not load any of the patches.

Load all the chromosomes in NoMerge DB

---

.travis.yml

Travis file has been changed to get the tests working on ensembl-branch-97 and server-config/110

New Travis file to facilitate NoMerge testing

---

modules/Bio/Vega/Transform/RegionToXML.pm

Code fix for ENSCORESW-3157. 
The code processes the transcripts that lie within the region selected by the user.

Code to handle overlapping transcripts

---

modules/Bio/Otter/Lace/Defaults.pm

Changed the server URL to point to the test server on otter-server VM

New test server on VM URL

---

modules/Bio/Otter/Lace/Client.pm

This changes fix underlying issues in the code found when working on ENSCORESW-3022.

Bio::Otter::Lace::Client updates

---

modules/Bio/Otter/Lace/AceDatabase.pm
modules/Bio/Vega/DBSQL/AuthorAdaptor.pm
modules/Bio/Vega/DBSQL/TranscriptAdaptor.pm

ENSCORESW-3191- Code required to recover a saved session. 
I'm sneaking in changes in TranscriptAdaptor.pm and AuthorAdaptor.pm which are required for saving a modified transcript annotation. These changes still does not completely resolve the transcript saving issue.

Code to recover a saved session

---

modules/Bio/Vega/DBSQL/AuthorAdaptor.pm
modules/Bio/Vega/DBSQL/TranscriptAdaptor.pm

Revert PR #61  to restore changes made to modules/Bio/Vega/DBSQL/AuthorAdaptor.pm and modules/Bio/Vega/DBSQL/TranscriptAdaptor.pm

Revert "Code to recover a saved session"

---

modules/Bio/Otter/Lace/Client.pm
modules/Bio/Otter/ServerAction/FindClones.pm
modules/CanvasWindow/SearchWindow.pm

Fixed clones search.
Problem was in hardcoded cs name and version, now it is taken from client request.

Fixed clones search

---

modules/Bio/Vega/AceConverter.pm
modules/Bio/Vega/Transform/FromHumAce.pm
modules/Bio/Vega/Utils/Attribute.pm

Adding selenocysteine as attribute to transcript. Tested.

Selenocystein fix

---

modules/Bio/Otter/Lace/Pfam.pm

Use the namespaceURI from XML when present or use normal https pfam
URI
Added a base variable for pfam so only one value needs to be changed
if needed
It seems that the resul_url has been changed and now returns a relative
URI, so we check if http is present at the beginning of the string

Add https to URI, use base pfam URI and check result_url has http

---

modules/Bio/Vega/Gene.pm
modules/Bio/Vega/Transcript.pm

This is for the Gene and Transcript object as status has been removed from the Core API but is still used by Otter at the moment

Bugfix: add status to the list of options of the method new

---

modules/Bio/Otter/Lace/AceDatabase.pm
modules/Bio/Otter/Lace/Client.pm
scripts/apache/nfetch

Right click in the blixem window did not work as the code was not updated to match the master branch. Blixem fetches the correct data.

Changes to get nfetch to work

---

modules/MenuCanvasWindow/TranscriptWindow.pm

Type menu now has hierarchy structure to fit in screen.

Type menu hierarchy done.

---

modules/Bio/Otter/MappingFetcher.pm

Fixed cads search, by removing hardcoded otter cs

Fix cs and csversion

---

scripts/apache/set_sequence_note

Notes is set considering cs

---

modules/Bio/Vega/Transform/RegionToXML.pm

Reverts Ensembl/ensembl-otter#97

Revert "Bugfix/array error"

---

modules/Bio/Otter/Lace/AceDatabase.pm

Error message added to convey that a larger set of clones should be loaded. Zmap does load if a larger set of clones is selected.

Code to deal with loading intronic regions.

---

modules/EditWindow/PfamWindow.pm
scripts/client/_otter_env_core.sh
scripts/client/_otter_macos_env.sh

Set the PERL5LIB dynamically based on INC from the chosen Perl. I also removed the PANGO stuff as it doesn't seem to be needed since version 1.38
This replace PR #30

Updates to make the creation of a dmg for OS X possible

---

modules/Bio/Otter/ServerAction/Region.pm

Store evidences Thibaut code adopted for otter

Store evidences

---

modules/Bio/Vega/DBSQL/StableIdAdaptor.pm

We use different syntax only for SQLite driver.

We added support of both db types for default values insert

---

modules/Bio/Otter/ServerAction/FindClones.pm

Debug output to find floating search bug

Debug output for search

---

modules/Bio/Otter/ServerAction/FindClones.pm

cs must be always chromosome, as this function is targeted to find chromosomes only. 
Otherwise if we find non-chromosome - even search will work, client will not be able to open containing dataSet, as it includes only chromosomes

Fix coordinate system name while we are finding chromosomes

---

modules/MenuCanvasWindow/TranscriptWindow.pm

The changes includes list of old biotypes excluded from dropdonw for more comfort UX.

We are excluding list of old transcript types from dropdown

---

modules/Bio/Otter/ServerAction/Region.pm

Reverts Ensembl/ensembl-otter#107

Revert "Revert "Store evidences""

---

modules/CanvasWindow/SequenceSetChooser.pm

Display CS name instead of Assembly in clone window

---

modules/Bio/Otter/ServerAction/Region.pm
modules/Bio/Vega/Exon.pm
modules/Bio/Vega/Transcript.pm

Fix 417 error, on some slices exons shoudn't be transfered to the toplevel

Store evidences fix

---

modules/Bio/Otter/Server/UserSpecies.pm

Added mouse test species details

Added mouse test species details

---

modules/Bio/Otter/Server/UserSpecies.pm

Species authorization for mouse_old and mouse_test

Changed mouse species details

---

modules/Bio/Otter/Server/UserSpecies.pm

Added herring species details.

Added herring and herring test species

---

scripts/apache/get_analyses_status

This is needed for herring and all new species

Do not check pipeline table if primary_assembly

---

modules/Bio/Otter/ServerAction/Region.pm

Bugfix, adding missing function for store evidences. Fixes a bunch of issues with 417 error when saving changes in otter.

Add missing set_hstart_hend function

---

modules/Bio/Otter/Lace/DB.pm
modules/Bio/Otter/ServerAction/LoutreDB.pm
modules/Bio/Otter/ServerAction/Region.pm
modules/Bio/Otter/ServerAction/XML/Region.pm
modules/Bio/Vega/Region.pm
modules/Bio/Vega/Region/Store.pm
modules/Bio/Vega/Transform/XMLToRegion.pm
modules/MenuCanvasWindow/SessionWindow.pm
modules/MenuCanvasWindow/TranscriptWindow.pm

Apply this revert to fix the failing build
This reverts commit aaa2ce3d54acdc17a6bb75687de34d6346969904, reversing
changes made to 54ae21f9dc231e6f0998aebecb06bf9daa60d0a8.

Revert "Merge pull request #132 from thibauthourlier/hotfix/primary_assemblies"

---

modules/Bio/Otter/ServerAction/Region.pm

Remove debug msgs

---

modules/Bio/Otter/ServerAction/Region.pm

We return all store evidences code with removed lines that trimming exon. 
We remove them, because nether Thhibaut nor i remember why are they here.

Trim exon bug fix

---

.travis.yml
modules/Bio/Otter/Lace/Client.pm
modules/Bio/Otter/ServerAction/FindClones.pm
modules/Bio/Otter/ServerAction/TSV/FindClones.pm
modules/CanvasWindow/SearchWindow.pm
modules/CanvasWindow/SequenceSetChooser.pm

New species like e.g. herring haven't got a coordinate system
'chromosome' yet, but only a 'primary assembly'. Add code for client and
server to support this.
Also added correct keyboard focus for search.

Support search in species with only primary_asmbly

---

modules/Bio/Otter/ServerAction/Region.pm
modules/Bio/Vega/DBSQL/GeneAdaptor.pm
modules/Bio/Vega/Transform/FromHumAce.pm

https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3390
https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3411

Gene authorship and persistent attributes issue

---

.travis.yml

Otter docker test suite ubuntu and ensembl update
- Update ensembl version to 108
- Update Ubuntu version to 22.04

Otter docker test suite ubuntu and ensembl update

---

modules/Bio/Otter/Server/UserSpecies.pm

Adding the following species to main branch
- cattle (bos taurus)
- horse (equus caballus)
- rat (rattus norvegicus)
- sheep (ovis aries rambouillet)
As per [ENSCORESW-4268](https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-4268)

Added species: bos_taurus,equus_caballus,rattus_norvegicus,ovis_aries

---

modules/Bio/Otter/Server/UserSpecies.pm

Added new dummy species (copy of human) to test Apollo3

Added apollo3 test dummy species

---

modules/Bio/Vega/Utils/GeneTranscriptBiotypeStatus.pm

Added new biotypes to the client to match the server configuration as per https://github.com/Ensembl/server-config/pull/95 and https://github.com/Ensembl/server-config/pull/96
Also added minor aesthetic changes.
Tested manually locally.

New transcript biotypes for human T2T
